version: "3.8"

services:

  keycloak-db:
    image: postgres:14.0-alpine
    container_name: keycloak-db
    volumes:
      - "./.storage/keycloak-db/data:/var/lib/postgresql/data"
    networks:
      - keycloak
    environment:
      - "POSTGRES_USER=${KEYCLOAK_DB_USER_NAME}"
      - "POSTGRES_PASSWORD=${KEYCLOAK_DB_USER_PASSWORD}"
      - "POSTGRES_DB=${KEYCLOAK_DB_TABLE_NAME}"
    restart: always

  keycloak:
    build: "./keycloak"
    container_name: keycloak
    volumes:
      - "./keycloak/todo-realm.json:/tmp/todo-realm.json"
    ports:
      - "8080:8080"
    networks:
      - keycloak
    environment:
      # Configure Account
      - "KEYCLOAK_USER=${KEYCLOAK_USER}"
      - "KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}"
      # Import the realm
      - "KEYCLOAK_IMPORT=/tmp/todo-realm.json"
      # Configure Database
      - "DB_VENDOR=${KEYCLOAK_VENDOR}"
      - "DB_ADDR=${KEYCLOAK_ADDR}"
      - "DB_PORT=${KEYCLOAK_DB_PORT}"
      - "DB_USER=${KEYCLOAK_DB_USER_NAME}"
      - "DB_PASSWORD=${KEYCLOAK_DB_USER_PASSWORD}"
      - "DB_DATABASE=${KEYCLOAK_DB_TABLE_NAME}"
    depends_on:
      - keycloak-db
    restart: always

  todo-frontend:
    build: "./todo-frontend"
    container_name: todo-frontend
    volumes:
      - "./todo-frontend/:/home/app"
    ports:
      - "3000:3000"
    networks:
      - frontend
    environment:
      - "HOST=0.0.0.0"
    restart: always

networks:
  keycloak:
  frontend:
