version: "3.8"

services:

  keycloak-db:
    image: postgres:14.0-alpine
    container_name: keycloak-db
    volumes:
      - "./.storage/keycloak-db/data:/var/lib/postgresql/data"
    networks:
      - keycloak
    environment:
      - "POSTGRES_USER=${KEYCLOAK_DB_USER_NAME}"
      - "POSTGRES_PASSWORD=${KEYCLOAK_DB_USER_PASSWORD}"
      - "POSTGRES_DB=${KEYCLOAK_DB_TABLE_NAME}"
    restart: unless-stopped

  keycloak:
    build: "./keycloak"
    container_name: keycloak
    ports:
      - "8080:8080"
    networks:
      - keycloak
    environment:
      # Configure Account
      - "KEYCLOAK_USER=${KEYCLOAK_USER}"
      - "KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}"
      # Configure Database
      - "DB_VENDOR=${KEYCLOAK_VENDOR}"
      - "DB_ADDR=${KEYCLOAK_ADDR}"
      - "DB_PORT=${KEYCLOAK_DB_PORT}"
      - "DB_USER=${KEYCLOAK_DB_USER_NAME}"
      - "DB_PASSWORD=${KEYCLOAK_DB_USER_PASSWORD}"
      - "DB_DATABASE=${KEYCLOAK_DB_TABLE_NAME}"
    depends_on:
      - keycloak-db
    restart: unless-stopped

  todo-frontend:
    build: "./todo-frontend"
    container_name: todo-frontend
    volumes:
      - "./todo-frontend/:/home/app"
      # Don't override node_modules which can be empty on the local machine
      - "/home/app/node_modules"
    ports:
      - "3000:3000"
    networks:
      - frontend
    environment:
      - "HOST=0.0.0.0"
    restart: unless-stopped

  todo-db:
    image: "amazon/dynamodb-local:1.17.0"
    container_name: "todo-db"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - "./.storage/todo-db/data:/home/dynamodblocal/data"
    ports: # Only required for the Setup-Process
      - "8000:8000" # After setup, feel free to disable this port-mapping
    networks:
      - backend
    restart: unless-stopped

  todo-service:
    build: "./todo-service"
    container_name: todo-service
    volumes:
      - "./todo-service/:/home/app"
      # Don't override node_modules which can be empty on the local machine
      - "/home/app/node_modules"
    ports:
      - "4000:4000"
    networks:
      - backend
      - keycloak
    environment:
      - "SERVER_ENVIRONMENT_SETTING=${SERVER_ENVIRONMENT_SETTING}"
      - "SERVER_PORT=${SERVER_PORT}"
      - "KEYCLOAK_URL=${KEYCLOAK_URL}"
      - "KEYCLOAK_REALM=${KEYCLOAK_REALM}"
      - "KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}"
      - "KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}"
      - "KEYCLOAK_REALM_PUBLIC_KEY=${KEYCLOAK_REALM_PUBLIC_KEY}"
      - "DYNAMODB_REGION=${DYNAMODB_REGION}"
      - "DYNAMODB_ENDPOINT=${DYNAMODB_ENDPOINT}"
      - "DYNAMODB_TABLE_NAME=${DYNAMODB_TABLE_NAME}"
      - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
      - "REGION=${DYNAMODB_REGION}"
    depends_on:
      - todo-db
    restart: unless-stopped

networks:
  keycloak:
  frontend:
  backend:
